version: "3.8"

services:
  backend:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis
    ports:
      - "6379:6379"
